stages:
    - deploy
    - build

variables:
    DOCKER_IMAGE: $DOCKER_IMAGE
    DOCKER_CONTAINER: $DOCKER_CONTAINER
    PORT: $PORT
    CI: 'false'

cache:
    paths:
        - node_modules

deploy:
    stage: deploy
    only:
        - master
    script:
        - pwd
        - git pull origin master
        - echo "Deployed staging successfully"

build:
    stage: build
    only:
        - master
    script:
        - echo "Building the project"
        - sudo docker build -t $CI_REGISTRY_IMAGE -f Dockerfile .
        - sudo docker run -d -p $PORT:$PORT --name $DOCKER_CONTAINER $CI_REGISTRY_IMAGE
